src/dimcal/dcal/urls.py
from django.conf.urls import url

#from . import views
from .views import *

app_name = 'dcal'
urlpatterns = [
    url(r'^$',      IndexView.as_view(), name='index'),
    url(r'^[Aa][Bb][Oo][Uu][Tt]$', AboutView.as_view(), name='about'),

    url(r'^(?P<year>\d{4})/$', YearView.as_view(), name='year'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$', YearMonthView.as_view(month_format='%m'), name='year_month'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$', YearMonthDayView.as_view(), name='year_month_day'),

    url(r'^(?P<country>[a-zA-Z][a-zA-Z]_?\w*)/$', CountryView.as_view(), name='country'),

    url(r'^(?P<country>[a-zA-Z][a-zA-Z]_?\w*)/(?P<year>[0-9]{4})/$',
        CountryYearView.as_view(),
        name='country_year'),

]

src/dimcal/dimcal/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^[dD][iI][mM]_[cC][aA][lL][eE][nN][dD][aA][rR]/', include('dcal.urls')),
    url(r'^[bB][uU][iI][lL][dD]/', include('buildsql.urls')),

    url(r'^[aA][dD][mM][iI][nN]/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/dimcal/dcal/models.py
from __future__ import unicode_literals

from django.db import models


class DimCalendar(models.Model):
    dim_calendar_pk                = models.IntegerField(primary_key=True)
    calendar_date                  = models.DateField()
    #
    calc_full_moon                 = models.NullBooleanField()
    #
    calc_western_epiphany          = models.NullBooleanField()
    calc_western_clean_mon         = models.NullBooleanField()
    calc_western_annunciation      = models.NullBooleanField()
    calc_western_ash_wed           = models.NullBooleanField()
    calc_western_palm_sun          = models.NullBooleanField()
    calc_western_holy_thu          = models.NullBooleanField()
    calc_western_good_fri          = models.NullBooleanField()
    calc_western_easter_sat        = models.NullBooleanField()
    calc_western_easter_sun        = models.NullBooleanField()
    calc_western_easter_mon        = models.NullBooleanField()
    calc_western_all_saints        = models.NullBooleanField()
    calc_western_immaculate_con    = models.NullBooleanField()
    calc_western_christmas_eve     = models.NullBooleanField()
    calc_western_christmas         = models.NullBooleanField()
    calc_western_ascension_thu     = models.NullBooleanField()
    calc_western_assumption        = models.NullBooleanField()
    calc_western_whit_sun          = models.NullBooleanField()
    calc_western_whit_mon          = models.NullBooleanField()
    calc_western_corpuschristi_thu = models.NullBooleanField()
    #
    calc_eastern_easter_sun        = models.NullBooleanField()
    #
    hol_at                     = models.NullBooleanField()
    hol_be                     = models.NullBooleanField()
    hol_bg                     = models.NullBooleanField()
    hol_ca_ab                  = models.NullBooleanField()
    hol_ca_bc                  = models.NullBooleanField()
    hol_ca_fed                 = models.NullBooleanField()
    hol_ca_mb                  = models.NullBooleanField()
    hol_ca_nat                 = models.NullBooleanField()
    hol_ca_nb                  = models.NullBooleanField()
    hol_ca_nl                  = models.NullBooleanField()
    hol_ca_ns                  = models.NullBooleanField()
    hol_ca_nt                  = models.NullBooleanField()
    hol_ca_nu                  = models.NullBooleanField()
    hol_ca_on                  = models.NullBooleanField()
    hol_ca_pe                  = models.NullBooleanField()
    hol_ca_qc                  = models.NullBooleanField()
    hol_ca_sk                  = models.NullBooleanField()
    hol_ca_yt                  = models.NullBooleanField()
    hol_cy                     = models.NullBooleanField()
    hol_cz                     = models.NullBooleanField()
    hol_de_bw                  = models.NullBooleanField()
    hol_de_by                  = models.NullBooleanField()
    hol_de_be                  = models.NullBooleanField()
    hol_de_bb                  = models.NullBooleanField()
    hol_de_gdr                 = models.NullBooleanField()
    hol_de_hb                  = models.NullBooleanField()
    hol_de_hh                  = models.NullBooleanField()
    hol_de_he                  = models.NullBooleanField()
    hol_de_mv                  = models.NullBooleanField()
    hol_de_ni                  = models.NullBooleanField()
    hol_de_nw                  = models.NullBooleanField()
    hol_de_rp                  = models.NullBooleanField()
    hol_de_sl                  = models.NullBooleanField()
    hol_de_sn                  = models.NullBooleanField()
    hol_de_st                  = models.NullBooleanField()
    hol_de_sh                  = models.NullBooleanField()
    hol_de_th                  = models.NullBooleanField()
    hol_dk                     = models.NullBooleanField()
    hol_ee                     = models.NullBooleanField()
    hol_es_nat                 = models.NullBooleanField()
    hol_fi                     = models.NullBooleanField()
    hol_fr                     = models.NullBooleanField()
    hol_gb_eng_wls             = models.NullBooleanField()
    hol_gb_sct                 = models.NullBooleanField()
    hol_gb_nir                 = models.NullBooleanField()
    hol_gr                     = models.NullBooleanField()
    hol_hr                     = models.NullBooleanField()
    hol_hu                     = models.NullBooleanField()
    hol_ie                     = models.NullBooleanField()
    hol_it                     = models.NullBooleanField()
    hol_lt                     = models.NullBooleanField()
    hol_lu                     = models.NullBooleanField()
    hol_lv                     = models.NullBooleanField()
    hol_mg                     = models.NullBooleanField()
    hol_mt                     = models.NullBooleanField()
    hol_nl                     = models.NullBooleanField()
    hol_pa                     = models.NullBooleanField()
    hol_pl                     = models.NullBooleanField()
    hol_pt                     = models.NullBooleanField()
    hol_ro                     = models.NullBooleanField()
    hol_se                     = models.NullBooleanField()
    hol_si                     = models.NullBooleanField()
    hol_sk                     = models.NullBooleanField()
    hol_st                     = models.NullBooleanField()
    hol_us_fed                 = models.NullBooleanField()
    hol_uy                     = models.NullBooleanField()
    hol_za                     = models.NullBooleanField()




    class Meta:
        db_table = 'dim_calendar'

    # static methods would look better but then can't get to a model static method from a template
    def _get_countries(self):
        return [att[4:] for att in dir(DimCalendar) if att.startswith('hol_') ]

    def _get_date_countries(self):
        return [att for att in self._get_countries() if getattr(self, 'hol_'+att)]

    countries      = property(_get_countries)
    date_countries = property(_get_date_countries)


    def _get_calcs(self):
        return [att[5:] for att in dir(DimCalendar) if att.startswith('calc_')
                and not att.startswith('calc_tbc') ]

    def _get_date_calcs(self):
        return [att for att in self._get_calcs() if getattr(self, 'calc_'+att) ]

    calcs      = property(_get_calcs)
    date_calcs = property(_get_date_calcs)

src/dimcal/dcal/views.py
from datetime import date

from django.shortcuts import render, get_object_or_404
from django.db import models
# Create your views here.
from django.http import HttpResponse
from django.views.generic.detail import DetailView
from django.views.generic.dates import YearArchiveView, MonthArchiveView
from .models import DimCalendar
from django.http import Http404
from django.views.generic import TemplateView, ListView

class AboutView( TemplateView):
    template_name = "dcal/about.html"


class IndexView( TemplateView):
    template_name = "dcal/index.html"

    def get_context_data(self, **kwargs):
        context = super(TemplateView, self).get_context_data(**kwargs)
        context['first_date'] = DimCalendar.objects.order_by('calendar_date').first()
        context['last_date']  = DimCalendar.objects.order_by('calendar_date').last()
        return context


class CountryView( ListView):
    template_name = "dcal/country.html"
    make_object_list = True


    def get_queryset(self):
        # DimCalendar will only have attributes for completed data sets
        page  = 'hol_' + self.kwargs['country'].lower()
        if hasattr(DimCalendar, page):
            filter_dict = {page: True}
            queryset = DimCalendar.objects.filter(models.Q(**filter_dict)).order_by('calendar_date')
            return queryset

        else:
            raise Http404('Oops, missing data set')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ListView, self).get_context_data(**kwargs)
        context['country'] = self.kwargs['country']
        return context




class CountryYearView( ListView):
    template_name = "dcal/country_year.html"
    make_object_list = True

    def get_queryset(self):
        # DimCalendar will only have attributes for completed data sets
        page = 'hol_' + self.kwargs['country'].lower()
        if hasattr(DimCalendar, page):
            filter_dict = {page: True}
            queryset = DimCalendar.objects.filter(
                models.Q(**filter_dict)).filter(
                calendar_date__year = self.kwargs['year']).order_by('calendar_date')
            return queryset

        else:
            raise Http404('Oops, missing data set')


    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ListView, self).get_context_data(**kwargs)
        context['country'] = self.kwargs['country']
        context['year']    = self.kwargs['year']
        return context



class YearView(YearArchiveView):
    queryset = DimCalendar.objects.all()
    date_field = 'calendar_date'
    make_object_list = True
    allow_future = True


class YearMonthView(MonthArchiveView):
    queryset = DimCalendar.objects.all()
    date_field = 'calendar_date'
    make_object_list = True
    allow_future = True

class YearMonthDayView(DetailView):
    #model = DimCalendar
    date_field = 'calendar_date'
    make_object_list = True
    allow_future = True

#    def get_queryset(self):
#        return DimCalendar.objects.all()
#                .filter(calendar_date__month =self.kwargs['month'])\
#                .filter(calendar_date__day = self.kwargs['day'])

    def get_object(self):
        return get_object_or_404(DimCalendar, calendar_date="{}-{}-{}".format(self.kwargs['year'], self.kwargs['month'],self.kwargs['day']))

src/dimcal/dcal/templates/dcal/about.html
{% extends 'dcal/base.html' %}
{% load bootstrap3 %}

{% block title %}About Dim_Calendar{% endblock %}

{% block content %}

<div>
A collection of public holiday data in SQL format, to use in a data warehouse.

Covering Jan 1970 - Jan 2038.
</div>

<div>
Now using Python's <a href="https://github.com/novafloss/workalendar">Workalendar</a> module for unit tests.

</div>

<div>
This data is provided as is under the terms of <a href="http://unlicense.org/">Unlicense</a>.

Alternatively you could license data from <a href="http://www.qppstudio.net">professionals</a>.
</div>

{% endblock %}

src/dimcal/dcal/templates/dcal/base.html
{% extends 'dcal/bootstrap.html' %}

{% load bootstrap3 %}

{% block bootstrap3_content %}
    <div class="container">
        <h1>{% block title %}(no title){% endblock %}</h1>

        <p>
            <a href="{% url 'dcal:index' %}">Home</a>
            <a href="{% url 'dcal:about' %}">About</a>
            <a href="https://github.com/gregn610/dimcal/releases">Download</a>
        </p>

        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}(no content){% endblock %}
    </div>

{% endblock %}

src/dimcal/dcal/templates/dcal/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}

{% block bootstrap3_title %}{% block title %}{% endblock %}{% endblock %}

src/dimcal/dcal/templates/dcal/country.html
{% extends 'dcal/base.html' %}
{% load bootstrap3 %}
{% load static %}
{% load range %}

{% block title %}Dim_Calendar Public Holidays{% endblock %}

{% block content %}

<h2>{{ country }}</h2>
    <div>
    See something not right? Please
<a href="https://github.com/gregn610/dimcal/issues/new?title={{ country }}&nbsp;{{ year }};body=hi,">open a ticket</a> or submit a pull request.
    </div>

<div>
    <table>
        <thead itemscope itemtype="https://schema.org/temporalCoverage" content="{{object_list.calendar_date|first|date:"Y"}}/{{object_list.calendar_date|last|date:"Y"}}">
        </thead>
        <tbody>
            {% for dc in object_list %}
            <tr itemscope itemtype="http://schema.org/BusinessEvent">
                <td>
                    <time itemprop="startDate" datetime="{{ dc.calendar_date|date:"Y-m-d" }}">{{ dc.calendar_date|date:"Y-m-d" }}</time>
                    <meta itemprop="name" content="Public Holiday">
                </td>
                <td itemprop="location" itemscope itemtype="http://schema.org/Country">
                    <meta itemprop="name"    content="{{ country }}">
                    <meta itemscope itemtype="http://schema.org/Text" itemprop="address" >
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<hr>
<a href="{% url 'dcal:index' %}">Home</a>

{% endblock %}

src/dimcal/dcal/templates/dcal/country_year.html
{% extends 'dcal/base.html' %}
{% load bootstrap3 %}
{% load static %}
{% load range %}

{% block title %}Dim_Calendar Public Holidays{% endblock %}

{% block content %}

<h2>{{ country }} {{year}}</h2>

    <div>
    See something not right? Please
<a href="https://github.com/gregn610/dimcal/issues/new?title={{ country }}&nbsp;{{ year }};body=hi,">open a ticket</a> or submit a pull request.
    </div>

<div>
    <table>
        <thead itemscope itemtype="https://schema.org/temporalCoverage" content="{{year|date:"Y"}}/{{year|date:"Y"|add:"1"}}">
        </thead>
        <tbody>
            {% for dc in object_list %}
            <tr itemscope itemtype="http://schema.org/BusinessEvent">
                <td>
                    <time itemprop="startDate" datetime="{{ dc.calendar_date|date:"Y-m-d" }}">{{ dc.calendar_date|date:"Y-m-d" }}</time>

                </td>
                <td><meta itemprop="name" content="Public Holiday">&nbsp;</td>
                <td itemprop="location" itemscope itemtype="http://schema.org/Country">
                    <meta itemprop="name"    content="{{ country }}">
                    <meta itemscope itemtype="http://schema.org/Text" itemprop="address" >
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

src/dimcal/dcal/templates/dcal/dimcalendar_archive_month.html
{% extends 'dcal/base.html' %}
{% load bootstrap3 %}
{% load static %}
{% load range %}

{% block title %}Dim_Calendar Public Holidays{% endblock %}

{% block content %}

<h2>{{ country }} {{ month|date:"M Y"}}</h2>

See something not right? Please
<a href="https://github.com/gregn610/dimcal/issues/new?title={{ country }}&nbsp;{{ year }};body=hi,">open a ticket</a> or submit a pull request.

<table>
    <thead>
        <meta itemscope itemtype="http://schema.org/addressCountry" content="{{ country }}">
        <meta itemscope itemtype="https://schema.org/temporalCoverage" content="{{month|date:"Y-m"}}-01/P1M">
    </thead>
    <tbody>


            {% for dc in dimcalendar_list %}
                {% if dc.date_countries|length %}

                    <tr itemscope itemtype="http://schema.org/BusinessEvent">
                        <td itemprop="startDate" datetime="{{ dc.calendar_date|date:"Y-m-d" }}" >
                            <a href="{% url 'dcal:year_month_day' dc.calendar_date|date:"Y" dc.calendar_date|date:"m" dc.calendar_date|date:"d" %}">{{ dc.calendar_date|date:"Y-m-d" }}</a>
                            <meta itemprop="name" content="Public Holiday">
                        </td>
                        <td>&nbsp;</td>
                        {% for cc in dc.date_countries %}
                        <td itemprop="location" itemscope itemtype="http://schema.org/Country">
                            <span itemprop="name"    content="{{ cc|upper }}">
                                <a href="{%url 'dcal:country' cc|upper %}">{{ cc|upper }}</a>
                            </span>
                            <meta itemscope itemtype="http://schema.org/Text" itemprop="address" >
                        </td>
                        {% endfor %}
                    </tr>

                {% endif %}
            {% endfor %}
    </tbody>
</table>

<hr>
<p>
    {% if previous_month %}
        <a href="{% url 'dcal:year_month' previous_month|date:"Y" previous_month|date:"m" %}">{{ previous_month|date:"M Y" }} &lt;&lt; </a>
    {% endif %}
    {% if next_month %}
        <a href="{% url 'dcal:year_month' next_month|date:"Y" next_month|date:"m" %}" }}"> &gt;&gt; {{ next_month|date:"M Y" }}</a>
    {% endif %}
</p>

{% endblock %}

src/dimcal/dcal/templates/dcal/dimcalendar_archive_year.html
{% extends 'dcal/base.html' %}
{% load bootstrap3 %}
{% load static %}
{% load range %}

{% block title %}Dim_Calendar Public Holidays{% endblock %}

{% block content %}

<div>
    <h2>{{ year|date:"Y" }}</h2>
    <div>
    See something not right? Please
<a href="https://github.com/gregn610/dimcal/issues/new?title={{ country }}&nbsp;{{ year }};body=hi,">open a ticket</a> or submit a pull request.
    </div>


    <table>
        <thead itemscope itemtype="https://schema.org/temporalCoverage" content="{{year|date:"Y"}}/{{year|date:"Y"|add:"1"}}">
        </thead>
        <tbody>
    {% for dc in dimcalendar_list %}
        {% if dc.date_countries|length %}

        <tr itemscope itemtype="http://schema.org/BusinessEvent">
            <td itemprop="startDate" datetime="{{ dc.calendar_date|date:"Y-m-d" }}">
                <nobr>
            <a href="{% url 'dcal:year_month' dc.calendar_date|date:"Y" dc.calendar_date|date:"m" %}">{{ dc.calendar_date|date:"Y-m" }}</a>&nbsp;-
            <a href="{% url 'dcal:year_month_day' dc.calendar_date|date:"Y" dc.calendar_date|date:"m" dc.calendar_date|date:"d" %}">{{ dc.calendar_date|date:"d" }}</a>
                </nobr>
                <meta itemprop="name" content="Public Holiday">
            </td>
            <td>&nbsp;</td>
            <td>
            {% for cc in dc.date_countries %}
                <span itemprop="location" itemscope itemtype="http://schema.org/Country">
                <a href="{% url 'dcal:country_year' cc|upper dc.calendar_date|date:"Y" %}" itemprop="name" content="{{ cc|upper }}">{{ cc|upper }}</a>
                <meta itemscope itemtype="http://schema.org/Text" itemprop="address" >
                </span>
            {% endfor %}
            </td>
        </tr>
        {% endif %}
    {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

src/dimcal/dcal/templates/dcal/dimcalendar_detail.html
{% extends 'dcal/base.html' %}
{% load bootstrap3 %}
{% load static %}
{% load range %}

{% block title %}Dim_Calendar Public Holidays{% endblock %}

{% block content %}

<h2>{{ dimcalendar.calendar_date|date:"Y-m-d" }}</h2>

    <div>
    See something not right? Please
<a href="https://github.com/gregn610/dimcal/issues/new?title={{ country }}&nbsp;{{ year }};body=hi,">open a ticket</a> or submit a pull request.
    </div>

<ul itemscope itemtype="https://schema.org/temporalCoverage" content="{{ dimcalendar.calendar_date|date:"Y-m-d" }}/P1D" >
    {% for cc in dimcalendar.date_countries %}
    <li><a href="{% url 'dcal:country' cc|upper %}" itemscope itemtype="http://schema.org/addressCountry">{{ cc|upper }}</a></li>
    {% endfor %}
</ul>

{% endblock %}