src/dimcal/buildsql/urls.py
from django.conf.urls import url

#from . import views
from .views import *

app_name = 'buildsql'
urlpatterns = [
    url(r'^$',
        SQLIndexView.as_view(),
        name='sqlindex'
        ),
#
    url(r'^(?P<dialect>[a-zA-Z][a-zA-Z]_?\w*)/[tT][aA][bB][lL][eE].[sS][qQ][lL]$',
        SQLTableView.as_view(content_type='text/plain; charset=utf-8'),
        name='sqltable'
        ),
    url(r'^(?P<dialect>[a-zA-Z][a-zA-Z]_?\w*)/[cC][oO][mM][mM][oO][nN].[sS][qQ][lL]$',
        SQLCommonView.as_view(content_type='text/plain; charset=utf-8'),
        name='sqlcommon'
        ),
    url(r'^(?P<dialect>[a-zA-Z][a-zA-Z]_?\w*)/[cC][aA][lL][cC][uU][lL][aA][tT][iI][oO][nN][sS].[sS][qQ][lL]$',
        SQLCalculationsView.as_view(content_type='text/plain; charset=utf-8'),
        name='sqlcalculations'
        ),
    url(r'^(?P<dialect>[a-zA-Z][a-zA-Z]_?\w*)/(?P<country>[a-zA-Z][a-zA-Z]_?\w*)/[dD][aA][tT][aA].[sS][qQ][lL]$',
        SQLDataView.as_view( content_type='text/plain; charset=utf-8'),
        name='sqldata'
        ),
]

src/dimcal/dcal/urls.py
from django.conf.urls import url

#from . import views
from .views import *

app_name = 'dcal'
urlpatterns = [
    url(r'^$',      IndexView.as_view(), name='index'),
    url(r'^[Aa][Bb][Oo][Uu][Tt]$', AboutView.as_view(), name='about'),

    url(r'^(?P<year>\d{4})/$', YearView.as_view(), name='year'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$', YearMonthView.as_view(month_format='%m'), name='year_month'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$', YearMonthDayView.as_view(), name='year_month_day'),

    url(r'^(?P<country>[a-zA-Z][a-zA-Z]_?\w*)/$', CountryView.as_view(), name='country'),

    url(r'^(?P<country>[a-zA-Z][a-zA-Z]_?\w*)/(?P<year>[0-9]{4})/$',
        CountryYearView.as_view(),
        name='country_year'),

]

src/dimcal/dimcal/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^[dD][iI][mM]_[cC][aA][lL][eE][nN][dD][aA][rR]/', include('dcal.urls')),
    url(r'^[bB][uU][iI][lL][dD]/', include('buildsql.urls')),

    url(r'^[aA][dD][mM][iI][nN]/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/dimcal/buildsql/models.py
from django.db import models

# Create your models here.

src/dimcal/buildsql/views.py
from functools import reduce

from django.db.models import Q
from django.http import Http404
from django.shortcuts import render
from django.db import models
# Create your views here.
from django.http import Http404
from dcal.models import DimCalendar
from django.views.generic import TemplateView, ListView

# Create your views here.
class SQLIndexView(TemplateView):
    """
    Index of countries and SQL dialects
    """
    template_name = "buildsql/index.html"

    def get_context_data(self, **kwargs):
        context = super(TemplateView, self).get_context_data(**kwargs)
        dc = DimCalendar()
        context['calcs'] = DimCalendar().calcs
        context['countries'] = DimCalendar().countries

        return context


class SQLTableView(TemplateView):
    """
    Tables & indexes
    """
    template_name = "buildsql/table.sql92.sql"

    def get_context_data(self, **kwargs):
        context = super(TemplateView, self).get_context_data(**kwargs)
        dc = DimCalendar()
        context['calcs'] = dc.calcs
        context['countries'] = dc.countries

        dialect = context['dialect'] or 'SQL92'
        dialect = dialect.upper()
        if dialect == 'MYSQL':
            self.template_name = "buildsql/table.mysql.sql"
        if dialect == 'TSQL':
            self.template_name = "buildsql/table.tsql.sql"
        if dialect == 'PLPGSQL':
            self.template_name = "buildsql/table.plpgsql.sql"

        return context


class SQLCommonView(TemplateView):
    """
    Insert keys
    """
    template_name = "buildsql/common.sql92.sql"

    def get_context_data(self, **kwargs):
        context = super(TemplateView, self).get_context_data(**kwargs)
        dc = DimCalendar()
        context['calcs'] = dc.calcs
        context['countries'] = dc.countries

        dialect = context['dialect'] or 'SQL92'
        dialect = dialect.upper()
        if dialect == 'MYSQL':
            self.template_name = "buildsql/common.mysql.sql"
        if dialect == 'TSQL':
            self.template_name = "buildsql/common.tsql.sql"
        if dialect == 'PLPGSQL':
            self.template_name = "buildsql/common.plpgsql.sql"

        return context


class SQLCalculationsView(TemplateView):
    """
    SQL Updates for calc_ columns
    """
    template_name = "buildsql/calc.sql92.sql"

    def get_queryset(self):
        dc = DimCalendar()

        queryset = DimCalendar.objects.raw("""
        SELECT *
        FROM dim_calendar
        WHERE
        """ + reduce(lambda x, y: x + """ OR
        """ + y, ['calc_{0} = True '.format(cc) for cc in dc.calcs]) + """
        ORDER BY calendar_date""")

        if list(queryset):
            return queryset
        else:
            raise Http404('Oops, no data found')

    def get_context_data(self, **kwargs):
        context = super(TemplateView, self).get_context_data(**kwargs)
        dc = DimCalendar()
        context['calcs'] = dc.calcs

        # bucket the Dim_Calendars by calculation column
        calculations_dict = {}
        for dc in self.get_queryset():
            for cc in ['calc_' + short_name for short_name in dc.calcs]:
                if getattr(dc, cc): # Is this calc column set on this Dim_Calendar.calendar_date ?
                    calculations_dict.setdefault(cc, []).append(dc.calendar_date)
        context['calculations_dict'] = calculations_dict

        dialect = context['dialect'] or 'SQL92'
        dialect = dialect.upper()
        if dialect == 'MYSQL':
            self.template_name = "buildsql/calc.mysql.sql"
        if dialect == 'TSQL':
            self.template_name = "buildsql/calc.tsql.sql"
        if dialect == 'PLPGSQL':
            self.template_name = "buildsql/calc.plpgsql.sql"

        return context


class SQLDataView(TemplateView):
    """
    SQL Updates for a dim_calendar country
    """
    template_name = "buildsql/data.sql92.sql"

    def get_queryset(self):
        # DimCalendar only has attributes for populated countries
        page = 'hol_' + self.kwargs['country'].lower()
        if hasattr(DimCalendar, page):
            filter_dict = {page: True}
            queryset = DimCalendar.objects.filter(models.Q(**filter_dict)).order_by('calendar_date')
            return queryset
        else:
            raise Http404('Oops, no data found')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(TemplateView, self).get_context_data(**kwargs)
        context['country_col'] = 'hol_' + self.kwargs['country'].lower()

        # bucket the Dim_Calendars by year
        year_dict = {}
        for dc in self.get_queryset():
            year_dict.setdefault(dc.calendar_date.year, []).append(dc)
        context['year_dict'] = year_dict

        dialect = context['dialect'] or 'SQL92'
        dialect = dialect.upper()
        if dialect == 'MYSQL':
            self.template_name = "buildsql/data.mysql.sql"
        if dialect == 'TSQL':
            self.template_name = "buildsql/data.tsql.sql"
        if dialect == 'PLPGSQL':
            self.template_name = "buildsql/data.plpgsql.sql"

        return context

src/dimcal/buildsql/templates/buildsql/index.html
{% extends 'dcal/base.html' %}
{% load bootstrap3 %}

{% block title %}Dim_Calendar SQL Index{% endblock %}

{% block content %}
<h2>Table &amp; Keys SQL</h2>
<table>
    <thead>
        <tr>
            <th colspan="5">Dialect</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><a href="{% url 'buildsql:sqltable' 'plpgsql' %}">PL/pgSQL Table</a></td>
            <td>&nbsp;&nbsp;</td>
            <td><a href="{% url 'buildsql:sqltable' 'mysql' %}">MySQL Table</a></td>
            {% comment %}
            <td>&nbsp;&nbsp;</td>
            <td><a href="{% url 'buildsql:sqltable' 'sql92' %}">SQL92 Table</a></td>
            <td>&nbsp;&nbsp;</td>
            <td><a href="{% url 'buildsql:sqltable' 'tsql' %}">T-SQL Table</a></td>
            {% endcomment %}
        </tr>
        <tr>
            <td><a href="{% url 'buildsql:sqlcommon' 'plpgsql' %}">PL/pgSQL Keys</a></td>
            <td>&nbsp;&nbsp;</td>
            <td><a href="{% url 'buildsql:sqlcommon' 'mysql' %}">MySQL Keys</a></td>

            {% comment %}
            <td>&nbsp;&nbsp;</td>
            <td><a href="{% url 'buildsql:sqlcommon' 'sql92' %}">SQL92 Keys</a></td>
            <td>&nbsp;&nbsp;</td>
            <td><a href="{% url 'buildsql:sqlcommon' 'tsql' %}">SQL Keys</a></td>
            {% endcomment %}
        </tr>
        <tr>
            <td><a href="{% url 'buildsql:sqlcalculations' 'plpgsql' %}">PL/pgSQL Calculations</a> ( Optional )</td>
            <td>&nbsp;&nbsp;</td>
            <td><a href="{% url 'buildsql:sqlcalculations' 'mysql' %}">MySQL Calculations</a> ( Optional )</td>

            {% comment %}
            <td>&nbsp;&nbsp;</td>
            <td><a href="{% url 'buildsql:sqlcalculations' 'sql92' %}">SQL92 Calculations</a> ( Optional )</td>
            <td>&nbsp;&nbsp;</td>
            <td><a href="{% url 'buildsql:sqlcalculations' 'tsql' %}">T-SQL Calculations</a> ( Optional )</td>
            {% endcomment %}
        </tr>
    </tbody>
</table>

<h2>Country Specific SQL</h2>
<table>
    <thead>
    <tr>
        <th>Country</th>
        <th colspan="5">Dialect</th>
    </tr></thead>
    <tbody>

    {% for country in countries %}
    <tr>
        <td>{{ country|upper }}</td>
        <td><a href="{% url 'buildsql:sqldata' 'plpgsql' country|upper %}">PL/pgSQL</a></td>
        <td>&nbsp;&nbsp;</td>
        <td><a href="{% url 'buildsql:sqldata' 'mysql' country|upper %}">MySQL</a></td>

        {% comment %}
        <td>&nbsp;&nbsp;</td>
        <td><a href="{% url 'buildsql:sqldata' 'sql92' country|upper %}">SQL92</a></td>
        <td>&nbsp;&nbsp;</td>
        <td><a href="{% url 'buildsql:sqldata' 'tsql' country|upper %}">T-SQL</a></td>

        {% endcomment %}
    </tr>

{% endfor %}
</tbody></table>

</body>
</html>
{% endblock %}